### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by ChiIlsans** [Gl2imm/RBX_Toolbox#12]
When I import any avatar, it simply gives me this error message. If I am doing something wrong on my end, then simply tell me what I am doing wrong.
![image](https://github.com/user-attachments/assets/60b4788f-75d8-4fc6-8678-4e067e01f643)

**Comment by Gl2imm** [comment]
Just try with blender 4.0 or lower. Seems like they updated some commands, so does not work with 4.3. Will need to wait for next toolbox update

**Comment by ChiIlsans** [comment]
Thank you.
