### ISSUE TITLE
Incorrect skin tone when importing Rthro avatars from Roblox

### ISSUE THREAD

**Issue by ghost** [Gl2imm/RBX_Toolbox#2]
Exactly as the issue title says. During import, no errors occur. However the character loaded has a different skin tone to the one that the player actually has. This has been an issue for me as I cannot get the proper skin tone unless I manually load the proper texture for it.

Screenshot of the bug:
<img width="1369" alt="image" src="https://github.com/Gl2imm/RBX_Toolbox/assets/100100163/949946ec-0a14-41dd-b4b0-b494912d9318">

**Comment by Gl2imm** [comment]
Thx for feedback.. Yep, i noticed it for the new heads as well.. When i checked, the usual texture that comes from roblox dont have the skin tone in it
![image](https://github.com/Gl2imm/RBX_Toolbox/assets/69973491/35beacb2-c31f-4476-ae80-21b4c693ff7a)

so im guessing the new items have now skin tone in the separate textures.. I will address this..

**Comment by Gl2imm** [comment]
By the way, i tried to export the character from studio and manually import it to blender, its a same issue..
i noticed now they pushed the skin tone into the shader itself, but then texture also is plugged there, so its blocking the color.. 
So i only see this as a fix to the issue for now.. still checking how to settle this auto..
![image](https://github.com/Gl2imm/RBX_Toolbox/assets/69973491/67ec1cfd-ba3b-4506-8461-b836e5ea8167)

**Comment by Gl2imm** [comment]
Added support for new Heads and Skinned characters in v.4.2
It does display properly now.

Get it here: https://github.com/Gl2imm/RBX_Toolbox/releases/tag/v.4.2
(Do restart Blender after update)
