### ISSUE TITLE
(feature request) Avatar import without idle pose

### ISSUE THREAD

**Issue by RanzerScore90** [Gl2imm/RBX_Toolbox#3]
I'm requesting a feature that allows you to import the avatar of a person, but without the idle pose so you can rig it correctly to be animated, It will help me a lot since I'm a GFX creator and it's pretty annoying to export an avatar from roblox studio then import it into blender, this is a really cool addon and it's really underrated

**Comment by Gl2imm** [comment]
Honestly, it's not possible. This is how Roblox shares the obj, some they share without pose, but some with. I can't do anything with that.
