### ISSUE TITLE
Feature to work with Blender 4.0

### ISSUE THREAD

**Issue by catafest** [Gl2imm/RBX_Toolbox#4]
I tested with Blender 4 and not work.
The Blender version I tested is : blender-4.0.0-alpha+main.67843e188b24-windows.amd64-release

**Comment by Andrej730** [comment]
@catafest hello! what exactly doesn't work? can you please post error messages you get?

**Comment by Gl2imm** [comment]
Suggest to use lower versions, like 3.6.. Blender updating too fast, wont have time to keep up with that. Maybe later will update for those version with long support (there are some that will be supported for few years)

**Comment by Gl2imm** [comment]
Fixed some of the importing issues in version 4.5 Toolbox
