### ISSUE TITLE
not an issue but

### ISSUE THREAD

**Issue by Dyzcroll** [Gl2imm/RBX_Toolbox#6]
I'm aware this is for bug reports, but I can't find where to request a character.

I have a quick request regarding the plugin. Would it be possible to include Roblox Mr. Crash and Mannequin Blocky as rigs? It would greatly benefit users like me who enjoy animating.

https://www.roblox.com/bundles/503/Mr-Crash
https://www.roblox.com/bundles/515/Mannequin-Blocky

I understand if it's not possible, but your consideration would be appreciated.

Thanks!

**Comment by Gl2imm** [comment]
I need to get these rigs from somewhere.. currently I don't have them
