### ISSUE TITLE
can't Install 

### ISSUE THREAD

**Issue by WahajPlayz** [Gl2imm/RBX_Toolbox#9]
My version is 4.0 blender And it showing this

<img width="1919" alt="image" src="https://github.com/Gl2imm/RBX_Toolbox/assets/161223768/b2dd125d-6a0d-4f60-827b-d9cc63865e61">

**Comment by Gl2imm** [comment]
Hi. The correct name in Blender should be like this

![image](https://github.com/Gl2imm/RBX_Toolbox/assets/69973491/f1a60b08-6af3-4ddd-90e0-7fc8f2cf3041)

The one you key in is just zip archive name.
